/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.smart.home.ui;

/**
 *
 * @author USER
 */
public class Inicio extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jpT = new javax.swing.JPanel();
        lblT = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        btnT = new javax.swing.JButton();
        jpP = new javax.swing.JPanel();
        lblP = new javax.swing.JLabel();
        txtP = new javax.swing.JTextField();
        btn2 = new javax.swing.JButton();
        jpS = new javax.swing.JPanel();
        lblS = new javax.swing.JLabel();
        txtS = new javax.swing.JTextField();
        btn3 = new javax.swing.JButton();
        jpI = new javax.swing.JPanel();
        lblE = new javax.swing.JLabel();
        txtI = new javax.swing.JTextField();
        txtE = new javax.swing.JTextField();
        btn4 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(680, 0));

        jpT.setBackground(new java.awt.Color(51, 0, 255));

        lblT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblT.setForeground(new java.awt.Color(255, 255, 255));
        lblT.setText("Total de clientes registrados");

        btnT.setBackground(new java.awt.Color(0, 0, 0));
        btnT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnT.setForeground(new java.awt.Color(255, 255, 255));
        btnT.setText("ver detalle");

        javax.swing.GroupLayout jpTLayout = new javax.swing.GroupLayout(jpT);
        jpT.setLayout(jpTLayout);
        jpTLayout.setHorizontalGroup(
            jpTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTLayout.createSequentialGroup()
                .addGroup(jpTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpTLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpTLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblT, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpTLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnT)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jpTLayout.setVerticalGroup(
            jpTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblT)
                .addGap(18, 18, 18)
                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnT)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jpP.setBackground(new java.awt.Color(0, 153, 51));

        lblP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblP.setForeground(new java.awt.Color(255, 255, 255));
        lblP.setText("Proyectos activos");

        btn2.setBackground(new java.awt.Color(0, 0, 0));
        btn2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("ver detalle");

        javax.swing.GroupLayout jpPLayout = new javax.swing.GroupLayout(jpP);
        jpP.setLayout(jpPLayout);
        jpPLayout.setHorizontalGroup(
            jpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPLayout.createSequentialGroup()
                .addGroup(jpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(txtP, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblP, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btn2)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jpPLayout.setVerticalGroup(
            jpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblP)
                .addGap(18, 18, 18)
                .addComponent(txtP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpS.setBackground(new java.awt.Color(0, 0, 153));

        lblS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblS.setForeground(new java.awt.Color(255, 255, 255));
        lblS.setText("Productos con stcok bajo");

        btn3.setBackground(new java.awt.Color(0, 0, 0));
        btn3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("ver detalle");

        javax.swing.GroupLayout jpSLayout = new javax.swing.GroupLayout(jpS);
        jpS.setLayout(jpSLayout);
        jpSLayout.setHorizontalGroup(
            jpSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSLayout.createSequentialGroup()
                .addGroup(jpSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpSLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jpSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblS, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtS, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpSLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btn3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpSLayout.setVerticalGroup(
            jpSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblS)
                .addGap(18, 18, 18)
                .addComponent(txtS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn3)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jpI.setBackground(new java.awt.Color(0, 153, 204));

        lblE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblE.setForeground(new java.awt.Color(255, 255, 255));
        lblE.setText("Ingresos y egresos del mes");

        btn4.setBackground(new java.awt.Color(0, 0, 0));
        btn4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("ver detalle");

        javax.swing.GroupLayout jpILayout = new javax.swing.GroupLayout(jpI);
        jpI.setLayout(jpILayout);
        jpILayout.setHorizontalGroup(
            jpILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpILayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(btn4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpILayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jpILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpILayout.createSequentialGroup()
                        .addComponent(lblE, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpILayout.createSequentialGroup()
                        .addComponent(txtI, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtE, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jpILayout.setVerticalGroup(
            jpILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblE)
                .addGap(18, 18, 18)
                .addGroup(jpILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btnT;
    private javax.swing.JPanel jpI;
    private javax.swing.JPanel jpP;
    private javax.swing.JPanel jpS;
    private javax.swing.JPanel jpT;
    private javax.swing.JLabel lblE;
    private javax.swing.JLabel lblP;
    private javax.swing.JLabel lblS;
    private javax.swing.JLabel lblT;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txtE;
    private javax.swing.JTextField txtI;
    private javax.swing.JTextField txtP;
    private javax.swing.JTextField txtS;
    // End of variables declaration//GEN-END:variables
}
