/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.smart.home.ui;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author USER
 */
public class Panel extends javax.swing.JFrame {

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
        initContent();
    }
    
    private void initContent(){
       ShowJPanel(new Inicio());
    }
    
    private void ShowJPanel (JPanel p){
       p.setSize(680,473);
       p.setLocation(0,0);
       
       conten.removeAll();
       conten.add(p, BorderLayout.CENTER);
       conten.revalidate();
       conten.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFi = new javax.swing.JButton();
        back = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        btnIni = new javax.swing.JButton();
        btnPro = new javax.swing.JButton();
        brnIn = new javax.swing.JButton();
        btnCli = new javax.swing.JButton();
        btnEm = new javax.swing.JButton();
        btnAg = new javax.swing.JButton();
        btnRep = new javax.swing.JButton();
        btnFi1 = new javax.swing.JButton();
        conten = new javax.swing.JPanel();

        btnFi.setBackground(new java.awt.Color(0, 0, 255));
        btnFi.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        btnFi.setForeground(new java.awt.Color(255, 255, 255));
        btnFi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/finanzas.png"))); // NOI18N
        btnFi.setText("Finanzas");
        btnFi.setBorder(null);
        btnFi.setBorderPainted(false);
        btnFi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFi.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnFi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 473));

        menu.setBackground(new java.awt.Color(0, 0, 255));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIni.setBackground(new java.awt.Color(0, 0, 255));
        btnIni.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        btnIni.setForeground(new java.awt.Color(255, 255, 255));
        btnIni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/house.png"))); // NOI18N
        btnIni.setText("Inicio                      ");
        btnIni.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnIni.setBorderPainted(false);
        btnIni.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIni.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnIni.setIconTextGap(1);
        btnIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniActionPerformed(evt);
            }
        });
        menu.add(btnIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, 56));

        btnPro.setBackground(new java.awt.Color(0, 0, 255));
        btnPro.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        btnPro.setForeground(new java.awt.Color(255, 255, 255));
        btnPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/proyecto.png"))); // NOI18N
        btnPro.setText("  Proyectos              ");
        btnPro.setBorder(null);
        btnPro.setBorderPainted(false);
        btnPro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPro.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProActionPerformed(evt);
            }
        });
        menu.add(btnPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 400, 56));

        brnIn.setBackground(new java.awt.Color(0, 0, 255));
        brnIn.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        brnIn.setForeground(new java.awt.Color(255, 255, 255));
        brnIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inventario.png"))); // NOI18N
        brnIn.setText("Inventario              ");
        brnIn.setBorder(null);
        brnIn.setBorderPainted(false);
        brnIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        brnIn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        brnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnInActionPerformed(evt);
            }
        });
        menu.add(brnIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 410, 56));

        btnCli.setBackground(new java.awt.Color(0, 0, 255));
        btnCli.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        btnCli.setForeground(new java.awt.Color(255, 255, 255));
        btnCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clientes.png"))); // NOI18N
        btnCli.setText("Clientes                 ");
        btnCli.setBorder(null);
        btnCli.setBorderPainted(false);
        btnCli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCli.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliActionPerformed(evt);
            }
        });
        menu.add(btnCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 410, 56));

        btnEm.setBackground(new java.awt.Color(0, 0, 255));
        btnEm.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        btnEm.setForeground(new java.awt.Color(255, 255, 255));
        btnEm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleado.png"))); // NOI18N
        btnEm.setText("Empleados             ");
        btnEm.setBorder(null);
        btnEm.setBorderPainted(false);
        btnEm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEm.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnEm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmActionPerformed(evt);
            }
        });
        menu.add(btnEm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 410, 56));

        btnAg.setBackground(new java.awt.Color(0, 0, 255));
        btnAg.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        btnAg.setForeground(new java.awt.Color(255, 255, 255));
        btnAg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N
        btnAg.setText("Agregar  Usuario");
        btnAg.setBorder(null);
        btnAg.setBorderPainted(false);
        btnAg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAg.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgActionPerformed(evt);
            }
        });
        menu.add(btnAg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 400, 56));

        btnRep.setBackground(new java.awt.Color(0, 0, 255));
        btnRep.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        btnRep.setForeground(new java.awt.Color(255, 255, 255));
        btnRep.setText("  Reportes");
        btnRep.setBorder(null);
        btnRep.setBorderPainted(false);
        btnRep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRep.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRep.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepActionPerformed(evt);
            }
        });
        menu.add(btnRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 290, 56));

        btnFi1.setBackground(new java.awt.Color(0, 0, 255));
        btnFi1.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        btnFi1.setForeground(new java.awt.Color(255, 255, 255));
        btnFi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/finanzas.png"))); // NOI18N
        btnFi1.setText("Finanzas                 ");
        btnFi1.setBorder(null);
        btnFi1.setBorderPainted(false);
        btnFi1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFi1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnFi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFi1ActionPerformed(evt);
            }
        });
        menu.add(btnFi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 410, 56));

        conten.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout contenLayout = new javax.swing.GroupLayout(conten);
        conten.setLayout(contenLayout);
        contenLayout.setHorizontalGroup(
            contenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
        );
        contenLayout.setVerticalGroup(
            contenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backLayout = new javax.swing.GroupLayout(back);
        back.setLayout(backLayout);
        backLayout.setHorizontalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        backLayout.setVerticalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backLayout.createSequentialGroup()
                .addGroup(backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniActionPerformed
       ShowJPanel(new Inicio());
    }//GEN-LAST:event_btnIniActionPerformed

    private void btnProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProActionPerformed
        ShowJPanel(new Proyectos());
    }//GEN-LAST:event_btnProActionPerformed

    private void brnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnInActionPerformed
        ShowJPanel(new Inventario());
    }//GEN-LAST:event_brnInActionPerformed

    private void btnCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliActionPerformed
        ShowJPanel(new Cliente());
    }//GEN-LAST:event_btnCliActionPerformed

    private void btnEmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmActionPerformed
        ShowJPanel(new Empleados());
    }//GEN-LAST:event_btnEmActionPerformed

    private void btnRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepActionPerformed
        ShowJPanel(new Reportes());
    }//GEN-LAST:event_btnRepActionPerformed

    private void btnAgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgActionPerformed
        ShowJPanel(new Agregar());
    }//GEN-LAST:event_btnAgActionPerformed

    private void btnFi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFi1ActionPerformed
        ShowJPanel(new Financiero());
    }//GEN-LAST:event_btnFi1ActionPerformed

    private void btnFiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel back;
    private javax.swing.JButton brnIn;
    private javax.swing.JButton btnAg;
    private javax.swing.JButton btnCli;
    private javax.swing.JButton btnEm;
    private javax.swing.JButton btnFi;
    private javax.swing.JButton btnFi1;
    private javax.swing.JButton btnIni;
    private javax.swing.JButton btnPro;
    private javax.swing.JButton btnRep;
    private javax.swing.JPanel conten;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
