/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.smart.home.ui;

import com.smart.home.model.Proyectos;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;


public class Proyect extends javax.swing.JPanel {

    
    
    
    private ArrayList<Proyectos> Lis;   
    public Proyect() {
        Lis = new ArrayList<Proyectos>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblC = new javax.swing.JLabel();
        txtS = new javax.swing.JTextField();
        lblF = new javax.swing.JLabel();
        btnV = new javax.swing.JButton();
        cbI = new javax.swing.JComboBox<>();
        btnB = new javax.swing.JButton();
        spT = new javax.swing.JScrollPane();
        tblT = new javax.swing.JTable();
        jp1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbE = new javax.swing.JComboBox<>();
        txtF = new javax.swing.JTextField();
        txtN = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtE = new javax.swing.JTextField();
        txtI = new javax.swing.JTextField();
        btnG = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btnR = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        lblC.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lblC.setText("Gestión Proyectos");

        lblF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblF.setText("Filtrar:");

        btnV.setBackground(new java.awt.Color(0, 0, 0));
        btnV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnV.setForeground(new java.awt.Color(255, 255, 255));
        btnV.setText("Ver");
        btnV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVActionPerformed(evt);
            }
        });

        cbI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lista de Empledaos\t", "Pendiente" }));

        btnB.setBackground(new java.awt.Color(0, 0, 0));
        btnB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnB.setForeground(new java.awt.Color(255, 255, 255));
        btnB.setText("Ver");
        btnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBActionPerformed(evt);
            }
        });

        tblT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Encargardo", "Estado", "Fecha Inicio", "Fecha Fin"
            }
        ));
        tblT.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTMouseClicked(evt);
            }
        });
        spT.setViewportView(tblT);

        jp1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel2.setText("Datos del Proyecto");

        jLabel3.setText("ID");

        jLabel4.setText("Estado");

        jLabel5.setText("Fecha Inicio:");

        jLabel6.setText("Nombre:");

        cmbE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lista de Empledaos\t", "Pendiente" }));

        jLabel7.setText("Encargado:");

        btnG.setBackground(new java.awt.Color(204, 204, 204));
        btnG.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnG.setText("Guardar");
        btnG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGActionPerformed(evt);
            }
        });

        btnE.setBackground(new java.awt.Color(204, 204, 204));
        btnE.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnE.setText("Editar");
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });

        btnR.setBackground(new java.awt.Color(204, 204, 204));
        btnR.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnR.setText("Eliminar");
        btnR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRActionPerformed(evt);
            }
        });

        jLabel8.setText("Fecha Fin:");

        javax.swing.GroupLayout jp1Layout = new javax.swing.GroupLayout(jp1);
        jp1.setLayout(jp1Layout);
        jp1Layout.setHorizontalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jp1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(78, 78, 78)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbE, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btnG)
                        .addGap(18, 18, 18)
                        .addComponent(btnE)
                        .addGap(18, 18, 18)
                        .addComponent(btnR))
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp1Layout.createSequentialGroup()
                                .addComponent(txtI, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtE, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp1Layout.createSequentialGroup()
                                .addComponent(txtF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(35, 35, 35))
        );
        jp1Layout.setVerticalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5)))
                .addGap(8, 8, 8)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(6, 6, 6)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnR)
                    .addComponent(btnE)
                    .addComponent(btnG))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Buscar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblC, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblF, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbI, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnV, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(txtS, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnB, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(spT, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblC, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(btnV)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnB))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(cbI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addComponent(spT, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void Limpiar(){
     txtC.setText("");
     txtS.setText("");
     txtN.setText("");
     txtF.setText("");
     txtE.setText("");
     txtI.setText("");
    }
    private void btnGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGActionPerformed
        
     try {
         int id = Integer.parseInt(txtI.getText());
         String nombre = txtN.getText();
         String encargado = cmbE.getSelectedItem().toString();
         String estado = txtE.getText();
         String fechaInicioTexto = txtF.getText();
         String fechaFinTexto = txtC.getText();

    
    SimpleDateFormat entrada = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat salida = new SimpleDateFormat("MM/dd/yy");

    Date fechaInicio = entrada.parse(fechaInicioTexto);
    Date fechaFin = entrada.parse(fechaFinTexto);

    String Fe = salida.format(fechaInicio);
    String Fin = salida.format(fechaFin);
            
            
            Proyectos nuevo = new Proyectos(id, nombre, encargado, estado, Fe, Fin);
            Lis.add(nuevo);
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"verifique los datos");
        }
        Limpiar();
        verDatos();
    }//GEN-LAST:event_btnGActionPerformed
    private void verDatos(){
        String Mat[][] = new String [Lis.size()][6]; 
        Proyectos aux;
        for (int i = 0; i < Lis.size(); i++) {
            aux = Lis.get(i);
            Mat[i][0] = String.valueOf(aux.getID());
            Mat[i][1] = aux.getNombre();
            Mat[i][2] = aux.getEncargado();
            Mat[i][3] = aux.getEstado();
            Mat[i][4] = String.valueOf(aux.getFecha());
            Mat[i][5] = String.valueOf(aux.getFin());
        }
        tblT.setModel(new javax.swing.table.DefaultTableModel(
            Mat,
            new String [] {
                "ID", "Nombre", "Encargardo", "Estado", "Fecha Inicio", "Fecha Fin"
            }
        ));
    }
    
    
    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        int fila = tblT.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(null, "Seleccione una fila para editar.");
        return;
    }

    try {
        // Obtener los nuevos valores
        int id = Integer.parseInt(txtI.getText());
        String nombre = txtN.getText();
        String encargado = cmbE.getSelectedItem().toString();
        String estado = txtE.getText();
        String fecha = txtF.getText();
        String fin = txtC.getText();

        // Crear el nuevo objeto
        Proyectos editado = new Proyectos(id, nombre, encargado, estado, fecha, fin);

        // Reemplazar el registro en la lista
        Lis.set(fila, editado);

        // Actualizar la tabla
        verDatos();

        JOptionPane.showMessageDialog(null, "Registro actualizado correctamente.");
        Limpiar();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Verifique los datos antes de editar.");
    }

    }//GEN-LAST:event_btnEActionPerformed

    private void btnRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRActionPerformed
       int fila = tblT.getSelectedRow(); // obtiene la fila seleccionada

    if (fila == -1) {
        JOptionPane.showMessageDialog(null, "Seleccione una fila para eliminar.");
        return;
    }

    int confirmacion = JOptionPane.showConfirmDialog(null, "¿Desea eliminar este registro?", 
                                                     "Confirmar", JOptionPane.YES_NO_OPTION);

    if (confirmacion == JOptionPane.YES_OPTION) {
        Lis.remove(fila);
        verDatos();
        Limpiar();

        JOptionPane.showMessageDialog(null, "Registro eliminado correctamente.");
    }
    }//GEN-LAST:event_btnRActionPerformed

    private void tblTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTMouseClicked
        int fila = tblT.getSelectedRow();

    if (fila != -1) {
        txtI.setText(tblT.getValueAt(fila, 0).toString());
        txtN.setText(tblT.getValueAt(fila, 1).toString());
        cmbE.setSelectedItem(tblT.getValueAt(fila, 2).toString());
        txtE.setText(tblT.getValueAt(fila, 3).toString());
        txtF.setText(tblT.getValueAt(fila, 4).toString());
        txtC.setText(tblT.getValueAt(fila, 5).toString());
        }
    }//GEN-LAST:event_tblTMouseClicked

    private void btnVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVActionPerformed
        String encargadoSeleccionado = cmbE.getSelectedItem().toString();

    if (encargadoSeleccionado == null || encargadoSeleccionado.equals("")) {
        JOptionPane.showMessageDialog(null, "Seleccione un encargado primero.");
        return;
    }

    // Crear una lista temporal para los resultados
    ArrayList<Proyectos> filtrados = new ArrayList<>();

    for (Proyectos p : Lis) {
        if (p.getEncargado().equalsIgnoreCase(encargadoSeleccionado)) {
            filtrados.add(p);
        }
    }

    if (filtrados.isEmpty()) {
        JOptionPane.showMessageDialog(null, "No hay proyectos de este encargado.");
        return;
    }

    // Crear la matriz para mostrar en la tabla
    String Mat[][] = new String[filtrados.size()][6];
    for (int i = 0; i < filtrados.size(); i++) {
        Proyectos aux = filtrados.get(i);
        Mat[i][0] = Integer.toString(aux.getID());
        Mat[i][1] = aux.getNombre();
        Mat[i][2] = aux.getEncargado();
        Mat[i][3] = aux.getEstado();
        Mat[i][4] = aux.getFecha();
        Mat[i][5] = aux.getFin();
    }

    // Mostrar los resultados filtrados
    tblT.setModel(new javax.swing.table.DefaultTableModel(
        Mat,
        new String [] {
            "ID", "Nombre", "Encargado", "Estado", "Fecha Inicio", "Fecha Fin"
        }
    ));
    }//GEN-LAST:event_btnVActionPerformed

    private void btnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBActionPerformed
         String nombreBuscado = JOptionPane.showInputDialog("Ingrese el nombre del proyecto:");

    if (nombreBuscado == null || nombreBuscado.trim().equals("")) {
        return; // Cancelado o vacío
    }

    boolean encontrado = false;

    for (Proyectos p : Lis) {
        if (p.getNombre().equalsIgnoreCase(nombreBuscado.trim())) {
            // Mostrar la información encontrada
            JOptionPane.showMessageDialog(null,
                " Proyecto encontrado:\n\n" +
                "ID: " + p.getID() + "\n" +
                "Nombre: " + p.getNombre() + "\n" +
                "Encargado: " + p.getEncargado() + "\n" +
                "Estado: " + p.getEstado() + "\n" +
                "Fecha Inicio: " + p.getFecha() + "\n" +
                "Fecha Fin: " + p.getFin()
            );
            encontrado = true;
            break;
        }
    }

    if (!encontrado) {
        JOptionPane.showMessageDialog(null, "No se encontró ningún proyecto con ese nombre.");
    }
    }//GEN-LAST:event_btnBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnG;
    private javax.swing.JButton btnR;
    private javax.swing.JButton btnV;
    private javax.swing.JComboBox<String> cbI;
    private javax.swing.JComboBox<String> cmbE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jp1;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblF;
    private javax.swing.JScrollPane spT;
    private javax.swing.JTable tblT;
    private javax.swing.JTextField txtC;
    private javax.swing.JTextField txtE;
    private javax.swing.JTextField txtF;
    private javax.swing.JTextField txtI;
    private javax.swing.JTextField txtN;
    private javax.swing.JTextField txtS;
    // End of variables declaration//GEN-END:variables
}
