/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

/**
 *
 * @author USER
 */
public class Empleados extends javax.swing.JFrame {

    /**
     * Creates new form Empleados
     */
    public Empleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel1.setText("Gestión Empleados");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 170, 40);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 3, 12)); // NOI18N
        jLabel2.setText("Registrar Empleado");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 150, 30);

        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 50, 50, 16);

        jLabel4.setText("Cargo");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 100, 32, 16);

        jLabel5.setText(" DNI");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(220, 50, 50, 16);

        jLabel6.setText("Celular");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(400, 50, 35, 16);

        jLabel7.setText("Rol");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(230, 110, 17, 16);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(20, 70, 130, 22);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(220, 70, 90, 22);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(400, 70, 110, 22);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(20, 120, 120, 22);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(230, 130, 190, 22);

        jButton1.setText("Guardar");
        jPanel1.add(jButton1);
        jButton1.setBounds(50, 170, 72, 23);

        jButton2.setText("Editar");
        jPanel1.add(jButton2);
        jButton2.setBounds(150, 170, 72, 23);

        jButton3.setText("Eliminar");
        jPanel1.add(jButton3);
        jButton3.setBounds(240, 170, 72, 23);

        jButton4.setText("Limpiar");
        jPanel1.add(jButton4);
        jButton4.setBounds(330, 170, 72, 23);

        jButton5.setText("Salir");
        jPanel1.add(jButton5);
        jButton5.setBounds(430, 170, 72, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 40, 560, 200);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "DNI", "Celular", "Rol", "Cargo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 290, 510, 130);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Filtrar:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 250, 40, 16);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(80, 250, 130, 22);

        jButton6.setText("Ver");
        getContentPane().add(jButton6);
        jButton6.setBounds(220, 250, 50, 23);

        jButton7.setText("Ver");
        getContentPane().add(jButton7);
        jButton7.setBounds(470, 250, 50, 23);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Buscar:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(290, 250, 50, 16);

        setSize(new java.awt.Dimension(608, 445));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
